
name: Website

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - run: git tag --sort=committerdate | tail -1
      - uses: olafurpg/setup-scala@v13
      - run: sbt compileDocs
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: npm publish  
        run: sbt publishWebsite
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

